apiVersion: v1
kind: Pod
metadata:
  labels:
    run: database
  name: database
  namespace: sqldb
spec:
  containers:
  - name: database
    image: 168491602991.dkr.ecr.us-east-1.amazonaws.com/sqldb-repo:v1
    resources: {}
    ports:
    - containerPort: 3306
      protocol: TCP
    envFrom:
    - secretRef:
        name: mypassword