apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deploy-v2
  namespace: webapp
  labels:
    app: employees
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v2
  template:
    metadata:
      labels:
        app: employees
        version: v2
    spec:
      containers:
      - name: webapp-v2
        image: 168491602991.dkr.ecr.us-east-1.amazonaws.com/webapp-repo:v2
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: mypassword
        env: 
          - name: DBPORT
            value: "3306"
          - name: DBHOST
            value: "sqldb-service.sqldb.svc.cluster.local"